language: elixir
elixir:
  - '1.9'

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
  - mix sobelow -i Config.HTTPS --exit

after_success:
  - bash <(curl -s https://codecov.io/bash)