coverage:
  status:
    project:
      default:
        target: 95
        threshold: 5
        base: parent
    patch:
      default:
        target: 90
        threshold: 5
        base: parent
ignore:
  - "lib/ttt/application.ex"
  - "lib/ttt_web.ex"
  - "lib/ttt_web/channels/user_socket.ex"
  - "lib/ttt_web/endpoint.ex"
  - "lib/ttt_web/gettext.ex"
  - "lib/ttt_web/views/error_helpers.ex"
  - "lib/ttt_web/views/error_view"
  - "lib/ttt_web/views/layout_view.ex"
  - "lib/ttt_web/views/page_view.ex"
  - "test/support/channel_case.ex"
  - "test/support/conn_case.ex"